# Vercel へのデプロイを待ち、テストを実行する
# テスト(tests/screenshots.spec.js) にはVercel側Production URL(https://playwright-lesson.vercel.app/) を指定してある

name: ci
on:
  push:
    branches: [CI]

jobs:
  wait_for_vercel:
    name: Wait for vercel
    runs-on: ubuntu-latest
    outputs:
      preview_url: ${{ steps.waitForVercelPreviewDeployment.outputs.url }}
    steps:
      - name: Wait for Vercel preview deployment to be ready
        uses: patrickedqvist/wait-for-vercel-preview@v1.2.0
        id: waitForVercelPreviewDeployment
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          max_timeout: 120
  tests:
    name: End-to-end tests
    needs: wait_for_vercel
    runs-on: ubuntu-latest
    steps:
# GitHub Actions の仮想マシン(ubuntu-latest) 上に本リポジトリーのCIブランチをclone.
# https://github.com/actions/checkout
      - uses: actions/checkout@v3
        with:
          ref: CI
      - uses: actions/setup-node@v2
        with:
          node-version: '14.x'
      - name: Install dependencies
        run: yarn
      - name: Install Playwright
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: yarn playwright test
# Vercel のProduction を常に参照するのであれば、この環境変数の設定は不要
# もし環境変数を設定するなら、tests/screenshots.spec.js 側でもこの変数を参照するように作り直す必要がある
#        env:
#          PLAYWRIGHT_TEST_BASE_URL: ${{ needs.wait_for_vercel.outputs.preview_url }}
