name: Playwright Tests
on:
  push:
    branches: [ main, master, ci-test ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
# これだけではPlaywright が扱うフォントに影響が出なかった. もうひと工夫必要だ
#    - name: Install font
#      run: sudo apt install fonts-noto-cjk fonts-noto-cjk-extra fontconfig && fc-cache -fv
    - uses: actions/setup-node@v2
      with:
        node-version: '14.x'
    - name: Install dependencies
      run: yarn
    - name: Install Playwright
      run: npx playwright install --with-deps
    - name: Run Playwright tests
      run: yarn playwright test --workers 2
    - uses: actions/upload-artifact@v2
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
