#name: Playwright Tests
#on:
#  push:
#    branches: [ main, master ]
#  pull_request:
#    branches: [ main, master ]
#jobs:
#  test:
#    timeout-minutes: 60
#    runs-on: ubuntu-latest
#    steps:
#    - uses: actions/checkout@v2
#    - uses: actions/setup-node@v2
#      with:
#        node-version: '14.x'
#    - name: Install dependencies
#      run: yarn
#    - name: Install Playwright
#      run: npx playwright install --with-deps
#    - name: Run Playwright tests
#      run: yarn playwright test
#    - uses: actions/upload-artifact@v2
#      if: always()
#      with:
#        name: playwright-report
#        path: playwright-report/
#        retention-days: 30

name: ci
on:
  push:
    branches: [main,master]

jobs:
  wait_for_vercel:
    name: Wait for vercel
    runs-on: ubuntu-latest
    outputs:
      preview_url: ${{ steps.waitForVercelPreviewDeployment.outputs.url }}
    steps:
      - name: Wait for Vercel preview deployment to be ready
        uses: patrickedqvist/wait-for-vercel-preview@v1.2.0
        id: waitForVercelPreviewDeployment
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          max_timeout: 120
  tests:
    name: End-to-end tests
    needs: wait_for_vercel
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14.x'
#      - uses: microsoft/playwright-github-action@v1
#      - run: npm install --include=dev
#      - run: npm test
#        env:
#          VERCEL_URL: ${{ needs.wait_for_vercel.outputs.preview_url }}
#          VERCEL_ENV: preview
      - name: Install dependencies
        run: yarn
      - name: Install Playwright
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: yarn playwright test
        env:
          PLAYWRIGHT_TEST_BASE_URL: ${{ needs.wait_for_vercel.outputs.preview_url }}
#
#         env:
#           VERCEL_URL: ${{ needs.wait_for_vercel.outputs.preview_url }}
#           VERCEL_ENV: preview
#  pa11y:
#    name: Accessibility tests
#    needs: wait_for_vercel
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v2
#      - uses: actions/setup-node@v1
#        with:
#          node-version: 14.x
#      - run: npm install -g pa11y-ci
#      - run: pa11y-ci --sitemap ${{ needs.wait_for_vercel.outputs.preview_url }}/sitemap.xml
